### PR TITLE
Adds try/catch to checkExisting function

### PR DESCRIPTION
**Pull request by colinwebdev**
Addresses issue #17 by implementing a try/catch wrapper inside checkExisting(). This function is called before the user is able to create a database, and did not contain any logic to address what to do if the database has not yet been entered.

### CODE REVIEW

**Comment by eishiya** [comment]
Thanks for the fix!

However, I don't understand why the issue happened in the first place, since the code check that the database exists before running checkExisting, and it only exists if connectDB connected successfully. Perhaps something in PHP8 changed to where unset properties are now truthy instead of falsy? If that's the case, perhaps the more appropriate fix should be to edit `connectDB()` to explicitly set `$this->db` to `false` if the connection has an error, rather than merely leaving it unset.

A possible edge case that setting `$this->db` to `false` should fix is that connectDB, which runs multiple times in firstrun.php, will leave a precious dangling DB connection object even if the last requested connection fails, which may become invalid if the user or server is messing with the database at the same time. Is it possible that this happened to you?

**Comment by colinwebdev** [comment]
@eishiya You told me you'd rather that people contribute to Grawlix than trying to build something fresh. Now that I had the time to do so, I was going to do just that. But if this is the sort of response I can expect with something as minor as adding like 3 lines of incredibly simple code, I dread what I'd be met with if I tried something more complicated. Best of luck to you, I'll be devoting my time to other projects.

**Comment by eishiya** [comment]
I was trying to understand why the issue happened in the first place - my worry is that your fix is addressing the symptom of a deeper problem, which my alternative *maybe* fixes (hence the "perhaps"). I was hoping that you, since you're the one who experienced this issue, might be able to judge it better than I can.

**Comment by colinwebdev** [comment]
In what way is it only addressing a symptom? The issue does not arise at `$this->db` or anything in `connectDB()`. The error doesn't occur until you attempt to actually query the database in `checkExisting()`. Your proposed solution made zero sense give the actual error encountered. I put the error and stacktrace in the original issue. `checkExisting()` is just checking if it can find an existing user. If it returns an error obviously it couldn't find anything. An error would occur if the DB hadn't been configured yet, if the DB had been renamed for some reason, or if it had been corrupted or altered. All situations in which you would want that particular function to return false as it could not find what it was checking for. The "treating a symptom" fix was what I did every other time I've set up Grawlix for myself or someone else--just commented out everything inside `checkExisting()` so it wouldn't return an error. 

`checkExisting()` is a single time function that does one thing at initial set up and then is never used again. If there were deeper issues they would present themselves in other functions and other attempts to access the database. Plus, it's standard practice to anticipate and actually handle all the errors you may encounter, so you can display them or obscure them as needed. 

Also, I'm the only one who _reported_ the issue. It's highly likely some less than tech savvy person tried to set it up for themselves, saw either the PHP barf error or the generic internal server error and just gave up. I tested it in both my local system (a mac running XAMPP) and on my actual web host and encountered the exact same problem in both places. 

If you have further concerns about my fix, please elaborate as much as possible so I don't have to sit here guessing at what you mean.

**Comment by eishiya** [comment]
`checkExisting` should not run *at all* if a database has not been selected, because the `$this->db` object should be falsy (e.g. unset or `null`), and is checked for being truthy before `checkExisting` can run (`if ( $this->db )`). That's presumably why `checkExisting` had no safety checks inside it - it expects these checks to happen outside of it. But, clearly, the current safety checks are invalid or insufficient since you *did* run into a "no database selected" error inside `checkExisting`, and I'd like to figure out why.

The safety checks are inside the `connectDB` function, which runs before `checkExisting`, and sets the `$this->db` object that `checkExisting` relies on:
```php
protected function connectDB() {
	$info = $this->dbInfo;
	@$db = new mysqli($info['db_host'],$info['db_user'],$info['db_pswd'],$info['db_name']);
	if ( $db && ( !$db->connect_errno || $db->connect_errno == 0 ) ) {
		@$db->set_charset("utf8");
		$this->db = $db;
	}
}
```
As you can see, if there is any error when the connection happens (if `connect_errno` is set to any value other than 0), `$this->db` is not set at all - it should remain falsy (it starts out uninitialised). Theoretically, this means that if `connectDB` fails, i.e. that no database is selected, `checkExisting` should not run in the first place.

`connectDB` runs at every step of firstrun.php, but if the connection ever fails after succeeding at an earlier point, it never resets `$this->db` to a falsy state, which will cause errors as the earlier `$this->db` object is in an invalid state. In my earlier post, I asked whether it's possible that such an external database change happened in your case just to check whether this could've been the specific issue you ran into, because this is something that could cause `checkExisting` to be called and throw a "no database selected" error despite `$this->db` being truthy.

Making sure we set `$this->db` to `null` or `false` upon a failed connection should avoid problems such scenarios, and it would make the safety checks performed by `connectDB` actually valid on subsequent calls of it - right now, since the existing object is simply unchanged upon a failed connection, the old object just stays, despite probably no longer being valid.
A related issue is that PHP8+ doesn't like dereferencing unset values, such as in checks like `if ($this->db)` when `$this->db` is unset, and making sure we set `$this->db` to some falsy value will avoid that potential problem as well. I'd not be surprised if it was actually logging warnings every time it ran across such a check (which happens several times in firstrun.php).

*However*, and this is why my initial reply had so many words like "perhaps" and "possible" in it: since I don't know *why* in your scenario `$this->db` was truthy but still resulted in an unusable connection, I don't know whether this fix would solve the issue. Maybe it's a good idea to have both checks, or maybe we need to do some additional checks in `connectDB` to make sure the mysqli object is actually usable. Or maybe I'm missing something else.

**Comment by colinwebdev** [comment]
"Setting `$this->db` to null or false upon a failed connection" is vastly different to your initial statement of "explicitly set `$this->db` to false." But that still would not resolve this error. 

I ran an extremely simple test. I pulled the connectDB into a file on its own, setting everything to an empty string, as it is set in the original file. It returns as if it connected successfully. The same thing occurs if all 4 variables are set to `null`. When you use PDO instead of mysqli you get an error as expected. 

Screenshot 2023-08-10 at 9 53 38 PM

There have been a lot of changes made to mysqli in the point updates of PHP 8, including tweaks to error reporting. I do not have the time or patience to track down the specifics for what would cause this particular behavior. You are welcome to investigate that yourself. You are also welcome to implement any other tweaks you want. I just reported the issue I was facing and offered a fix for it. I've made all the changes I'm going to make to this project.

**Pull request merged**
